services:
  mysqldb:
    image: mysql:lts
    restart: unless-stopped
    env_file: ./.env
    networks:
      - default
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DOCKER_PORT: ${MYSQL_DOCKER_PORT}
    networks:
      - default
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:

networks:
  default:
